spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/courseweb
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amodindupa@gmail.com
spring.mail.password=mpsy lpue daxr cfhn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

openrouter.api.key=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


